-- MySQL Script generated by MySQL Workbench
-- Tue Sep 23 09:49:00 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sgerp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sgerp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgerp` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `sgerp` ;

-- -----------------------------------------------------
-- Table `sgerp`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgerp`.`Usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `registroPersonal` VARCHAR(5) NOT NULL,
  `nombreCompleto` VARCHAR(100) NOT NULL,
  `correoElectronico` VARCHAR(100) NOT NULL,
  `contrasena` CHAR(64) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `registroPersonal_UNIQUE` (`registroPersonal` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgerp`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgerp`.`Roles` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idRol`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgerp`.`EntregasRecepcionesPuestos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgerp`.`EntregasRecepcionesPuestos` (
  `idEntregaRecepcionPuesto` INT NOT NULL AUTO_INCREMENT,
  `datosGenerales` TEXT NOT NULL,
  `informeAsuntosTramite` TEXT NOT NULL,
  `otrosHechos` TEXT NOT NULL,
  `recursosFinancieros` TEXT NOT NULL,
  `recursosHumanos` TEXT NOT NULL,
  `recursosMateriales` TEXT NOT NULL,
  `situacionPresupuestoArea` TEXT NOT NULL,
  `situacionProgramatica` TEXT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idEntregaRecepcionPuesto`),
  INDEX `fk_EntregasRecepcionesPuestos_Trabajadores1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_EntregasRecepcionesPuestos_Usuarios`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `sgerp`.`Usuarios` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgerp`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgerp`.`Categorias` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgerp`.`Comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgerp`.`Comentarios` (
  `idComentario` INT NOT NULL AUTO_INCREMENT,
  `textoComentario` TEXT NOT NULL,
  `idCategoria` INT NOT NULL,
  `idEntregaRecepcionPuesto` INT NOT NULL,
  `idTrabajador` INT NOT NULL,
  PRIMARY KEY (`idComentario`),
  INDEX `fk_Comentarios_Categorías1_idx` (`idCategoria` ASC) VISIBLE,
  INDEX `fk_Comentarios_EntregasRecepcionesPuestos1_idx` (`idEntregaRecepcionPuesto` ASC) VISIBLE,
  INDEX `fk_Comentarios_Trabajadores1_idx` (`idTrabajador` ASC) VISIBLE,
  CONSTRAINT `fk_Comentarios_Categorias`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `sgerp`.`Categorias` (`idCategoria`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentarios_EntregasRecepcionesPuestos`
    FOREIGN KEY (`idEntregaRecepcionPuesto`)
    REFERENCES `sgerp`.`EntregasRecepcionesPuestos` (`idEntregaRecepcionPuesto`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentarios_Trabajadores`
    FOREIGN KEY (`idTrabajador`)
    REFERENCES `sgerp`.`Usuarios` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgerp`.`Evidencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgerp`.`Evidencias` (
  `idEvidencia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `evidencia` MEDIUMBLOB NOT NULL,
  `idEntregaRecepcionPuesto` INT NOT NULL,
  `idCategoria` INT NOT NULL,
  PRIMARY KEY (`idEvidencia`),
  INDEX `fk_Evidencias_EntregasRecepcionesPuestos1_idx` (`idEntregaRecepcionPuesto` ASC) VISIBLE,
  INDEX `fk_Evidencias_Categorías1_idx` (`idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Evidencias_EntregasRecepcionesPuestos`
    FOREIGN KEY (`idEntregaRecepcionPuesto`)
    REFERENCES `sgerp`.`EntregasRecepcionesPuestos` (`idEntregaRecepcionPuesto`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evidencias_Categorias`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `sgerp`.`Categorias` (`idCategoria`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgerp`.`EntregasRecepcionesPuestosRecibidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgerp`.`EntregasRecepcionesPuestosRecibidas` (
  `idEntregaRecepcionPuestoRecibida` INT NOT NULL AUTO_INCREMENT,
  `Aceptacion` TINYINT(1) NULL,
  `idUsuario` INT NOT NULL,
  `idEntregaRecepcionPuesto` INT NOT NULL,
  PRIMARY KEY (`idEntregaRecepcionPuestoRecibida`),
  INDEX `fk_EntregasRecepcionesPuestosRecibidas_Trabajadores1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_EntregasRecepcionesPuestosRecibidas_EntregasRecepcionesP_idx` (`idEntregaRecepcionPuesto` ASC) VISIBLE,
  CONSTRAINT `fk_EntregasRecepcionesPuestosRecibidas_Usuarios`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `sgerp`.`Usuarios` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EntregasRecepcionesPuestosRecibidas_EntregasRecepcionesPuestos`
    FOREIGN KEY (`idEntregaRecepcionPuesto`)
    REFERENCES `sgerp`.`EntregasRecepcionesPuestos` (`idEntregaRecepcionPuesto`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgerp`.`UsuariosRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgerp`.`UsuariosRoles` (
  `idUsuario` INT NOT NULL,
  `idRol` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `idRol`),
  INDEX `fk_UsuariosRoles_Usuarios1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_UsuariosRoles_Roles1_idx` (`idRol` ASC) VISIBLE,
  CONSTRAINT `fk_UsuariosRoles_Usuarios`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `sgerp`.`Usuarios` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UsuariosRoles_Roles`
    FOREIGN KEY (`idRol`)
    REFERENCES `sgerp`.`Roles` (`idRol`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
